"""add recurring to transactions

Revision ID: 49c0b73d9d99
Revises: d853d87405c4
Create Date: 2026-09-09 01:32:47.880760

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49c0b73d9d99"
down_revision: Union[str, None] = "d853d87405c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("recurring", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "recurring")
    # ### end Alembic commands ###
